package com.meliorix.coolstore;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PromoEvent implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PromoEvent() {
    }

}