package com.meliorix.coolstore;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ShoppingCartItem implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ShoppingCartItem() {
    }

}