package com.meliorix.coolstore;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ShoppingCart implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Shopping Cart Promotional Savings")
   private java.lang.Double cartItemPromoSavings;
   @org.kie.api.definition.type.Label(value = "Shopping Cart Item Total")
   private java.lang.Double carItemTotal;
   @org.kie.api.definition.type.Label(value = "Shopping Cart Total")
   private java.lang.Double cartTotal;
   @org.kie.api.definition.type.Label(value = "Shipping Promotional Savings")
   private java.lang.Double shippingPromoSavings;
   @org.kie.api.definition.type.Label(value = "Shipping Total")
   private java.lang.Double shippingTotal;
   @org.kie.api.definition.type.Label(value = "Shopping Cart Item List")
   private java.util.List<com.meliorix.coolstore.ShoppingCartItem> shoppingCartItemList;

   public ShoppingCart()
   {
   }

   public java.lang.Double getCartItemPromoSavings()
   {
      return this.cartItemPromoSavings;
   }

   public void setCartItemPromoSavings(java.lang.Double cartItemPromoSavings)
   {
      this.cartItemPromoSavings = cartItemPromoSavings;
   }

   public java.lang.Double getCarItemTotal()
   {
      return this.carItemTotal;
   }

   public void setCarItemTotal(java.lang.Double carItemTotal)
   {
      this.carItemTotal = carItemTotal;
   }

   public java.lang.Double getCartTotal()
   {
      return this.cartTotal;
   }

   public void setCartTotal(java.lang.Double cartTotal)
   {
      this.cartTotal = cartTotal;
   }

   public java.lang.Double getShippingPromoSavings()
   {
      return this.shippingPromoSavings;
   }

   public void setShippingPromoSavings(java.lang.Double shippingPromoSavings)
   {
      this.shippingPromoSavings = shippingPromoSavings;
   }

   public java.lang.Double getShippingTotal()
   {
      return this.shippingTotal;
   }

   public void setShippingTotal(java.lang.Double shippingTotal)
   {
      this.shippingTotal = shippingTotal;
   }

   public java.util.List<com.meliorix.coolstore.ShoppingCartItem> getShoppingCartItemList()
   {
      return this.shoppingCartItemList;
   }

   public void setShoppingCartItemList(
         java.util.List<com.meliorix.coolstore.ShoppingCartItem> shoppingCartItemList)
   {
      this.shoppingCartItemList = shoppingCartItemList;
   }

   public ShoppingCart(
         java.lang.Double cartItemPromoSavings,
         java.lang.Double carItemTotal,
         java.lang.Double cartTotal,
         java.lang.Double shippingPromoSavings,
         java.lang.Double shippingTotal,
         java.util.List<com.meliorix.coolstore.ShoppingCartItem> shoppingCartItemList)
   {
      this.cartItemPromoSavings = cartItemPromoSavings;
      this.carItemTotal = carItemTotal;
      this.cartTotal = cartTotal;
      this.shippingPromoSavings = shippingPromoSavings;
      this.shippingTotal = shippingTotal;
      this.shoppingCartItemList = shoppingCartItemList;
   }

}