package com.meliorix.coolstore;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ShoppingCartItem implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Item ID")
   private java.lang.String itemId;
   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Price")
   private java.lang.Double price;
   @org.kie.api.definition.type.Label(value = "Promotional Savings")
   private java.lang.Double promoSavings;
   @org.kie.api.definition.type.Label(value = "Quantity")
   private java.lang.Integer quantity;
   @org.kie.api.definition.type.Label(value = "Shopping Cart")
   private com.meliorix.coolstore.ShoppingCart shoppingCart;

   public ShoppingCartItem()
   {
   }

   public java.lang.String getItemId()
   {
      return this.itemId;
   }

   public void setItemId(java.lang.String itemId)
   {
      this.itemId = itemId;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Double getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Double price)
   {
      this.price = price;
   }

   public java.lang.Double getPromoSavings()
   {
      return this.promoSavings;
   }

   public void setPromoSavings(java.lang.Double promoSavings)
   {
      this.promoSavings = promoSavings;
   }

   public java.lang.Integer getQuantity()
   {
      return this.quantity;
   }

   public void setQuantity(java.lang.Integer quantity)
   {
      this.quantity = quantity;
   }

   public com.meliorix.coolstore.ShoppingCart getShoppingCart()
   {
      return this.shoppingCart;
   }

   public void setShoppingCart(com.meliorix.coolstore.ShoppingCart shoppingCart)
   {
      this.shoppingCart = shoppingCart;
   }

   public ShoppingCartItem(java.lang.String itemId, java.lang.String name,
         java.lang.Double price, java.lang.Double promoSavings,
         java.lang.Integer quantity,
         com.meliorix.coolstore.ShoppingCart shoppingCart)
   {
      this.itemId = itemId;
      this.name = name;
      this.price = price;
      this.promoSavings = promoSavings;
      this.quantity = quantity;
      this.shoppingCart = shoppingCart;
   }

}